apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-controller
  namespace: edge-computing

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-controller-role
  namespace: edge-computing
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-controller-binding
  namespace: edge-computing
subjects:
- kind: ServiceAccount
  name: node-controller
  namespace: edge-computing
roleRef:
  kind: Role
  name: node-controller-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-controller-node-reader
subjects:
- kind: ServiceAccount
  name: node-controller
  namespace: edge-computing
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io