apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-service-account
  namespace: edge-computing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-service-node-reader
subjects:
- kind: ServiceAccount
  name: data-service-account
  namespace: edge-computing
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io