apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-controller
  namespace: edge-computing
spec:
  selector:
    matchLabels:
      app: node-controller
  template:
    metadata:
      labels:
        app: node-controller
    spec:
      serviceAccountName: node-controller
      containers:
      - name: node-controller
        image: gitlab.stud.atlantis.ugent.be:5050/rdupon/mp/node-controller:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
      imagePullSecrets:
        - name: gitlab-ugent-registry