apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: edge-node-services
  namespace: edge-computing
spec:
  selector:
    matchLabels:
      app: edge-node-services
  template:
    metadata:
      labels:
        app: edge-node-services
    spec:
      serviceAccountName: node-controller
      containers:
      - name: node-controller
        image: gitlab.stud.atlantis.ugent.be:5050/rdupon/mp/node-controller:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SCHEDULER_SERVICE_HOST
          value: "localhost"
        #- name: PREDICTION_SERVICE_HOST
        #  value: "localhost"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

      - name: scheduler-service
        image: gitlab.stud.atlantis.ugent.be:5050/rdupon/mp/scheduler-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: FLASK_APP
          value: "scheduler_service.py"
        - name: FLASK_PORT
          value: "8001"
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      imagePullSecrets:
        - name: gitlab-ugent-registry