apiVersion: v1
kind: ConfigMap
metadata:
  name: zware-taak
  namespace: edge-computing
  labels:
    target-node: 75d09997-8f8f-42d2-ab01-md-0-lj2dx-xv7jf
    processed: "false"
data:
  energy_requirement: "0.9"  # 90% CPU belasting
  priority: "9"             # Hoge prioriteit
  max_delay: "300"          # Maximaal 5 minuten uitstel
  duration: "180"           # 3 minuten uitvoeringstijd