apiVersion: v1
kind: ConfigMap
metadata:
  name: gemiddelde-taak
  namespace: edge-computing
  labels:
    target-node: 75d09997-8f8f-42d2-ab01-md-0-lj2dx-xv7jf
    processed: "false"
data:
  energy_requirement: "0.6"  # 60% CPU belasting
  priority: "5"             # Gemiddelde prioriteit
  max_delay: "1800"         # Max 30 minuten uitstel
  duration: "120"           # 2 minuten uitvoeringstijd