apiVersion: v1
kind: ConfigMap
metadata:
  name: lichte-taak
  namespace: edge-computing
  labels:
    target-node: 75d09997-8f8f-42d2-ab01-md-0-lj2dx-xv7jf
    processed: "false"
data:
  energy_requirement: "0.3"  # 30% CPU belasting
  priority: "2"             # Lagere prioriteit
  max_delay: "3600"         # Kan tot 1 uur worden uitgesteld
  duration: "30"            # 30 seconden uitvoeringstijd